UPDATE public.collection_rate AS cr
SET 
    last_refresh_date = null ,
    region = null ,
    shop = null ,
    unique_account_id = null ,
    customer_name = null ,
    customer_phone_1 = null ,
    customer_phone_2 = null ,
    ward = null ,
    location_customer_met_latitude = null ,
    location_customer_met_longitude = null ,
    esf_only_status = null ,
    sales_agent_name = null ,
    agent_id = null ,
    agent_status = null ,
    last_7_day_cr = null ,
    technician_name = null ,
    daily_rate = null ,
    consecutive_late_days = null ,
    sales_agent_mobile = null ,
    six_month_collection_rate = null ,
    installation_date = null ,
    cash_collected = null ,
    days_expected = null ,
    customer_age_tag = null ,
    total_expected_cash = null ,
    par_0_29 = null ,
    par_30_59 = null ,
    par_60_119 = null ,
    par_120 = null ,
    customersegment = null ,
    eligible = null 
FROM public.pb_agents AS pb
WHERE cr.last_refresh_date < current_date - 1;  -- Assuming unique_account_id is the primary key or a unique identifier