UPDATE public.collection_rate AS cr
SET 
    last_refresh_date = pb.last_refresh_date,
    region = pb.region,
    shop = pb.shop,
    unique_account_id = pb.unique_account_id,
    customer_name = pb.customer_name,
    customer_phone_1 = pb.customer_phone_1,
    customer_phone_2 = pb.customer_phone_2,
    ward = pb.ward,
    location_customer_met_latitude = pb.location_customer_met_latitude,
    location_customer_met_longitude = pb.location_customer_met_longitude,
    esf_only_status = pb.esf_only_status,
    sales_agent_name = pb.sales_agent_name,
    agent_id = pb.agent_id,
    agent_status = pb.agent_status,
    last_7_day_cr = pb.last_7_day_cr,
    technician_name = pb.technician_name,
    daily_rate = pb.daily_rate,
    consecutive_late_days = pb.consecutive_late_days,
    sales_agent_mobile = pb.sales_agent_mobile,
    six_month_collection_rate = pb.six_month_collection_rate,
    installation_date = pb.installation_date,
    cash_collected = pb.cash_collected,
    days_expected = pb.days_expected,
    customer_age_tag = pb.customer_age_tag,
    total_expected_cash = pb.total_expected_cash,
    par_0_29 = pb.par_0_29,
    par_30_59 = pb.par_30_59,
    par_60_119 = pb.par_60_119,
    par_120 = pb.par_120,
    customersegment = pb.customersegment,
    eligible = pb.eligible 
FROM public.pb_agents AS pb
WHERE cr.unique_account_id = pb.unique_account_id;  -- Assuming unique_account_id is the primary key or a unique identifier