UPDATE public.collection_rate
SET 
	last_refresh_date = pb_agents.last_refresh_date,
    region = pb_agents.region ,
    shop = pb_agents.shop ,
	unique_account_id = pb_agents.unique_account_id ,
	customer_name = pb_agents.customer_name ,
	customer_phone_1 = pb_agents.customer_phone_1 ,
	customer_phone_2 = pb_agents.customer_phone_2 ,
	ward = pb_agents.ward ,
	location_customer_met_latitude = pb_agents.location_customer_met_latitude ,
	location_customer_met_longitude = pb_agents.location_customer_met_longitude ,
	esf_only_status = pb_agents.esf_only_status ,
	sales_agent_name = pb_agents.sales_agent_name ,
	agent_id = pb_agents.agent_id ,
	agent_status = pb_agents.agent_status ,
	last_7_day_cr = pb_agents.last_7_day_cr ,
	technician_name = pb_agents.technician_name ,
	daily_rate = pb_agents.daily_rate ,
	consecutive_late_days = pb_agents.consecutive_late_days ,
	sales_agent_mobile = pb_agents.sales_agent_name ,
	six_month_collection_rate = pb_agents.six_month_collection_rate ,
	installation_date = pb_agents.installation_date ,
	cash_collected = pb_agents.cash_collected ,
	days_expected = pb_agents.days_expected ,
	customer_age_tag = pb_agents.customer_age_tag ,
	total_expected_cash = pb_agents.total_expected_cash ,
	par_0_29 = pb_agents.par_0_29 ,
	par_30_59 = pb_agents.par_30_59 ,
	par_60_119 = pb_agents.par_60_119 ,
	par_120 = pb_agents.par_120 ,
	customersegment = pb_agents.customersegment ,
	eligible = pb_agents.eligible 
FROM public.pb_agents
WHERE collection_rate.unique_account_id = pb_agents.unique_account_id;